remote_theme: just-the-docs/just-the-docs
title: Micro-Vision Go-To-Market Playbook
description: A comprehensive playbook for market entry and growth

color_scheme: light
search_enabled: true
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright © 2024 Micro-Vision"

# Navigation Structure
nav_external_links:
  - title: Initial Business Review
    url: https://docs.google.com/document/d/1aXJpgmOadniKRNhfkQcis9WEs9Ndf_5lwSzAEYEuxQ0/
    hide_icon: false
  - title: Targeting Strategies
    url: https://docs.google.com/document/d/1dHU0Ho-9S7LwnGJsDue7a2Fe6K76j_p1XmSqh3LOd0E/
    hide_icon: false
  - title: Messaging Guide
    url: https://docs.google.com/document/d/1aJBiUylxoeRJpl2HT-NRVJ1DP2rfSab_Is0G-ch6kIk/
    hide_icon: false