remote_theme: just-the-docs/just-the-docs

# Site Settings
title: Micro-Vision Go-To-Market Playbook
description: A comprehensive guide for market entry and growth
url: https://detroit-ish.github.io/Micro-Vision-Go-To-Market-Playbook

# Theme Settings
color_scheme: light
search_enabled: true
heading_anchors: true

# Aux links for upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/Detroit-ish/Micro-Vision-Go-To-Market-Playbook"

# Custom Colors
brand_color: "#0969DA"

# Footer Content
footer_content: "Copyright © 2024 Micro-Vision. All rights reserved."

# Collections
collections:
  sections:
    permalink: "/:collection/:path/"
    output: true

# Navigation Settings
navigation:
  - title: Home
    url: /
  - title: Quick Start
    url: /quick-start
  - title: Target Industries
    url: /industries
    children:
      - title: Engineering
        url: /industries/engineering
      - title: Architecture
        url: /industries/architecture
      - title: VFX/3D
        url: /industries/vfx
  - title: Playbook Sections
    url: /sections
    children:
      - title: Targeting
        url: /sections/targeting
      - title: Messaging
        url: /sections/messaging
      - title: Campaigns
        url: /sections/campaigns
