title: Micro-Vision Go-To-Market Playbook
description: A comprehensive guide for market entry and growth
remote_theme: just-the-docs/just-the-docs

# Color scheme and search
color_scheme: light
search_enabled: true

# Aux links (GitHub link)
aux_links:
  "View on GitHub":
    - "https://github.com/Detroit-ish/Micro-Vision-Go-To-Market-Playbook"

# Enable copy code button
enable_copy_code_button: true

# Navigation
nav:
  - Home
  - Executive Summary
  - Ideal Customer Profiles
  - Key Highlights
  - Targeting Strategy
  - Messaging and Branding
  - AI Business Assistant
  - How to Use This Playbook
